### ISSUE TITLE
[ORDER] Add Salclient FAQ REEEEEEEEEEEE

### ISSUE THREAD

**Issue by donkeyduper** [salc1-org/salbot#16]
# Conversation:
- What client does @SalC1 use?
- Future utility client.

**Comment by untuned** [comment]
with a link to https://www.futureclient.net/

**Comment by Herbastko** [comment]
<https://github.com/salc1-org/salbot/pull/17>

:thonk:

**Comment by Herbastko** [comment]
Woop. Great Kaktoos fixed this!
